"""Schema exports."""
from app.schemas.ai import (
    AiAdviceRequest,
    AiAdviceResponse,
    AiChatRequest,
    AiChatResponse,
    JumpRopeAnalyzeRequest,
    JumpRopeAnalyzeResponse,
)
from app.schemas.booking import (
    AlertInfo,
    AttendanceStats,
    BookingBase,
    BookingCancelRequest,
    BookingCreate,
    BookingListResponse,
    BookingRescheduleRequest,
    BookingResponse,
    BookingUpdate,
    CoachAvailableSlotsResponse,
    CoachAvailableTimeSlot,
    CoachDetailResponse,
    CoachFeedbackBase,
    CoachFeedbackCreate,
    CoachFeedbackResponse,
    CoachReplyRequest,
    CoachSlotBase,
    CoachSlotCreate,
    CoachSlotResponse,
    CoachSlotUpdate,
    DashboardOverview,
    MembershipCardBase,
    MembershipCardCreate,
    MembershipCardResponse,
    MembershipCardUpdate,
    MembershipRechargeRequest,
    RevenueStats,
    ReviewBase,
    ReviewCreate,
    ReviewResponse,
    StudentMembershipBase,
    StudentMembershipCreate,
    StudentMembershipResponse,
    TransactionBase,
    TransactionCreate,
    TransactionResponse,
)
from app.schemas.chat import (
    ConversationCreate,
    ConversationListResponse,
    ConversationResponse,
    MessageCreate,
    MessageListResponse,
    MessageResponse,
    UserBrief,
)
from app.schemas.course import (
    AttendanceBase,
    AttendanceCreate,
    AttendanceResponse,
    CheckInRequest,
    CourseBase,
    CourseCreate,
    CourseResponse,
    CourseUpdate,
    ScheduleBase,
    ScheduleCreate,
    ScheduleResponse,
    ScheduleUpdate,
    VenueBase,
    VenueCreate,
    VenueResponse,
)
from app.schemas.energy import (
    EnergyAccountResponse,
    EnergyAccountSummary,
    EnergyEarnRequest,
    EnergyEarnResponse,
    EnergyRuleBase,
    EnergyRuleCreate,
    EnergyRuleResponse,
    EnergyRuleUpdate,
    EnergySpendRequest,
    EnergySpendResponse,
    EnergyTransactionList,
    EnergyTransactionResponse,
    LeaderboardEntry,
    LeaderboardResponse,
)
from app.schemas.growth import (
    FitnessMetricBase,
    FitnessMetricCreate,
    FitnessMetricResponse,
    FitnessTestBase,
    FitnessTestCreate,
    FitnessTestResponse,
    GrowthProfile,
    RadarChartData,
    TrainingSessionBase,
    TrainingSessionCreate,
    TrainingSessionResponse,
)
from app.schemas.merchant import (
    MerchantBase,
    MerchantCreate,
    MerchantDetailResponse,
    MerchantListResponse,
    MerchantResponse,
    MerchantStatsResponse,
    MerchantUpdate,
    MerchantUserResponse,
    RedeemItemBase,
    RedeemItemCreate,
    RedeemItemListResponse,
    RedeemItemResponse,
    RedeemItemUpdate,
    RedeemOrderCreate,
    RedeemOrderListResponse,
    RedeemOrderResponse,
    RedeemOrderVerifyRequest,
    RedeemOrderVerifyResponse,
)
from app.schemas.notification import (
    NotificationBase,
    NotificationCreate,
    NotificationListResponse,
    NotificationReadRequest,
    NotificationResponse,
)
from app.schemas.role import (
    ApiResponse,
    MenuBase,
    MenuResponse,
    PermissionBase,
    PermissionResponse,
    RoleBase,
    RoleResponse,
    SwitchRoleRequest,
    SwitchRoleResponse,
    UserMenusResponse,
    UserPermissionsResponse,
    UserRolesResponse,
)
from app.schemas.user import (
    CoachBase,
    CoachCreate,
    CoachProfileResponse,
    CoachRegister,
    CoachResponse,
    EmailCodeLogin,
    EmailCodeRequest,
    EmailRegister,
    PasswordChange,
    PasswordReset,
    StudentBase,
    StudentCreate,
    StudentDetailResponse,
    StudentRegister,
    StudentResponse,
    StudentUpdate,
    Token,
    TokenRefresh,
    UserBase,
    UserCreate,
    UserDetailResponse,
    UserLogin,
    UserResponse,
    UserUpdate,
    WechatLogin,
    WechatPhoneLogin,
)

__all__ = [
    # User
    "UserBase", "UserCreate", "UserLogin", "WechatLogin", "WechatPhoneLogin",
    "EmailCodeRequest", "EmailCodeLogin", "EmailRegister",
    "PasswordReset", "PasswordChange",
    "UserUpdate", "UserResponse", "UserDetailResponse", "Token", "TokenRefresh",
    "StudentBase", "StudentCreate", "StudentRegister", "StudentUpdate", "StudentResponse",
    "StudentDetailResponse",
    "CoachBase", "CoachCreate", "CoachRegister", "CoachResponse", "CoachProfileResponse",
    # Growth
    "FitnessMetricBase", "FitnessMetricCreate", "FitnessMetricResponse",
    "FitnessTestBase", "FitnessTestCreate", "FitnessTestResponse",
    "RadarChartData", "GrowthProfile",
    "TrainingSessionBase", "TrainingSessionCreate", "TrainingSessionResponse",
    # Courses
    "CourseBase", "CourseCreate", "CourseUpdate", "CourseResponse",
    "VenueBase", "VenueCreate", "VenueResponse",
    "ScheduleBase", "ScheduleCreate", "ScheduleUpdate", "ScheduleResponse",
    "AttendanceBase", "AttendanceCreate", "CheckInRequest", "AttendanceResponse",
    # Booking
    "MembershipCardBase", "MembershipCardCreate", "MembershipCardUpdate", "MembershipCardResponse",
    "StudentMembershipBase", "StudentMembershipCreate", "StudentMembershipResponse",
    "MembershipRechargeRequest",
    "CoachSlotBase", "CoachSlotCreate", "CoachSlotUpdate", "CoachSlotResponse",
    "BookingBase", "BookingCreate", "BookingUpdate", "BookingResponse", "BookingListResponse",
    "BookingCancelRequest", "BookingRescheduleRequest",
    "TransactionBase", "TransactionCreate", "TransactionResponse",
    "ReviewBase", "ReviewCreate", "ReviewResponse", "CoachReplyRequest",
    "CoachFeedbackBase", "CoachFeedbackCreate", "CoachFeedbackResponse",
    "CoachDetailResponse", "CoachAvailableTimeSlot", "CoachAvailableSlotsResponse",
    "DashboardOverview", "AttendanceStats", "RevenueStats", "AlertInfo",
    # AI
    "JumpRopeAnalyzeRequest", "JumpRopeAnalyzeResponse",
    "AiAdviceRequest", "AiAdviceResponse",
    "AiChatRequest", "AiChatResponse",
    # Notification
    "NotificationBase", "NotificationCreate", "NotificationResponse",
    "NotificationListResponse", "NotificationReadRequest",
    # Chat
    "ConversationCreate", "ConversationResponse", "ConversationListResponse",
    "MessageCreate", "MessageResponse", "MessageListResponse",
    "UserBrief",
    # Energy
    "EnergyRuleBase", "EnergyRuleCreate", "EnergyRuleUpdate", "EnergyRuleResponse",
    "EnergyAccountResponse", "EnergyAccountSummary",
    "EnergyTransactionResponse", "EnergyTransactionList",
    "EnergyEarnRequest", "EnergyEarnResponse",
    "EnergySpendRequest", "EnergySpendResponse",
    "LeaderboardEntry", "LeaderboardResponse",
    # Merchant
    "MerchantBase", "MerchantCreate", "MerchantUpdate", "MerchantResponse",
    "MerchantListResponse", "MerchantDetailResponse",
    "RedeemItemBase", "RedeemItemCreate", "RedeemItemUpdate", "RedeemItemResponse",
    "RedeemItemListResponse",
    "RedeemOrderCreate", "RedeemOrderResponse", "RedeemOrderListResponse",
    "RedeemOrderVerifyRequest", "RedeemOrderVerifyResponse",
    "MerchantStatsResponse", "MerchantUserResponse",
    # RBAC
    "RoleBase", "RoleResponse", "UserRolesResponse",
    "PermissionBase", "PermissionResponse", "UserPermissionsResponse",
    "MenuBase", "MenuResponse", "UserMenusResponse",
    "SwitchRoleRequest", "SwitchRoleResponse",
    "ApiResponse",
]
